title: Programação Orientada a Gambiarra
email: josenaldo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Livro Programação Orientada a Gambiarra - Como garantir que o inferno seja uma amostra grátis do deu trabalho
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.livro-pog.com.br"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed
  - jekyll/scholar

# Social usernames/URLs
twitter_username: vudureverso
github_username:  josenaldo
instagram_username: vudureverso
reddit_username: vudureverso
linkedin_link: https://www.linkedin.com/in/josenaldo/
facebook_link: https://www.facebook.com/josenaldo.matos

# Required by template
css: "blue-grey"
scroll-cursor: "#00BCD4"
scroll-rail: "#0097A7"
highlighter: null #pygments
lsi: false
safe: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
permalink: pretty
exclude: [vendor]

# Coleções
collections_dir: collections
collections:
  capitulos:
    output: true
    
excerpt_separator: <!--more-->

# Valores default
defaults:
  - scope:
      path: ""
      type: "capitulos"
    values:
      image: default-image.jpg
      layout: "capitulo"
  - scope:
      path: ""
      type: "posts"
    values:
      image: default-cover.jpg
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "home"

scholar:
  style: associacao-brasileira-de-normas-tecnicas
  locale: pt-br
  source: ./_bibliography
  bibliography: library.bib
  relative: /capitulos/referencias/
